server {
    listen 80;
    server_name sensor-api.kentaiwami.com sensor-view.kentaiwami.com sensor-realtime-view.kentaiwami.com neko.kentaiwami.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name sensor-api.kentaiwami.com;
    ssl_certificate /etc/letsencrypt/live/sensor-api.kentaiwami.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sensor-api.kentaiwami.com/privkey.pem;
    location / { proxy_pass http://sensor-api:8080; proxy_set_header Host $host; }
}

server {
    listen 443 ssl;
    server_name sensor-view.kentaiwami.com;
    ssl_certificate /etc/letsencrypt/live/sensor-api.kentaiwami.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sensor-api.kentaiwami.com/privkey.pem;
    location / { proxy_pass http://sensor-view:8080; proxy_set_header Host $host; }
}

server {
    listen 443 ssl;
    server_name sensor-realtime-view.kentaiwami.com;
    ssl_certificate /etc/letsencrypt/live/sensor-api.kentaiwami.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sensor-api.kentaiwami.com/privkey.pem;
    location / { proxy_pass http://sensor-realtime-view:8080; proxy_set_header Host $host; }
}

server {
    listen 443 ssl;
    server_name neko.kentaiwami.com;
    ssl_certificate /etc/letsencrypt/live/sensor-api.kentaiwami.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sensor-api.kentaiwami.com/privkey.pem;
    location / { proxy_pass http://neko:8080; proxy_set_header Host $host; }
}
